apiVersion: v1
kind: Service
metadata:
  name: aris-api-tmpl
  namespace: aris-api-tmpl
spec:
  type: ClusterIP
  selector:
    app: aris-api-tmpl
  ports:
    - name: http
      port: 8080
      targetPort: http
