version: '3'

services:
  postgresql:
    image: postgres:15
    container_name: postgresql
    restart: always
    # ports:
    #   - 5432:5432
    environment:
      - ../env/postgresql.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hcd233 -d tmpl-db"]
      interval: 5s
      retries: 10

  redis:
    image: bitnami/redis:latest
    container_name: redis
    restart: always
    # ports:
    #   - 6379:6379
    env_file:
      - ../env/redis.env
    volumes:
      - redis-data:/bitnami/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
    #   - 9000:9000
      - 9090:9090
    env_file:
      - ../env/minio.env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
    

  db-migrate:
    image: ghcr.io/hcd233/go-backend-tmpl:master
    container_name: db-migrate
    restart: no
    env_file:
      - ../env/api.env
    depends_on:
      postgresql:
        condition: service_healthy
    command: ["/app/go-backend-tmpl", "database", "migrate"]

  go-backend-tmpl:
    image: ghcr.io/hcd233/go-backend-tmpl:master
    container_name: go-backend-tmpl
    restart: always
    ports:
      - 8170:8080
    env_file:
      - ../env/api.env
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: ["/app/go-backend-tmpl", "server", "start", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  postgresql-data:
    name: postgresql-data
    external: true
  redis-data:
    name: redis-data
    external: true
  minio-data:
    name: minio-data
    external: true

# docker volume create postgresql-data 
# docker volume create redis-data
# docker volume create minio-data
# docker compose -f docker/docker-compose.yml up -d